events {}

http {
    upstream task_backend {
        least_conn;
        server doctask-manager-flask1-1:8000;
        server doctask-manager-flask2-1:8000;
    }

    limit_req_zone $binary_remote_addr zone=api_limit:10m rate=10r/s;

    server {
        listen 80;
        server_name localhost;
        return 301 https://$host$request_uri;
    }

    server {
        listen 443 ssl;
        server_name localhost;

        ssl_certificate /etc/nginx/ssl/selfsigned.crt;
        ssl_certificate_key /etc/nginx/ssl/selfsigned.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        location /static/ {
            alias /usr/share/nginx/html/static/;
        }

        location / {
            limit_req zone=api_limit burst=20 nodelay;

            proxy_pass http://task_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
